# Generated by Django 6.0.2 on 2026-04-10 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_name",
                    models.CharField(max_length=100, verbose_name="表单名称"),
                ),
                (
                    "table_name_list",
                    models.JSONField(default=list, verbose_name="表名列表"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "表单配置",
                "verbose_name_plural": "表单配置",
                "db_table": "work_tools2_formconfig",
            },
        ),
        migrations.CreateModel(
            name="FormQueryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50, verbose_name="标签")),
                (
                    "field_type",
                    models.CharField(
                        default="text", max_length=20, verbose_name="字段类型"
                    ),
                ),
                ("binding_key", models.CharField(max_length=50, verbose_name="绑定键")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "connected_table",
                    models.JSONField(default=list, verbose_name="关联表"),
                ),
                (
                    "valid_rule",
                    models.CharField(
                        choices=[
                            ("required", "必填"),
                            ("requiredReverse", "不必填"),
                            ("defaultNull", "默认空值"),
                            ("defaultField", "默认字段"),
                        ],
                        default="required",
                        max_length=20,
                        verbose_name="验证规则",
                    ),
                ),
                (
                    "default_value",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="默认值"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "form_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_items",
                        to="work_tools2.formconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "查询字段配置",
                "verbose_name_plural": "查询字段配置",
                "db_table": "work_tools2_formqueryitem",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="FormUpdateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50, verbose_name="标签")),
                (
                    "field_type",
                    models.CharField(max_length=20, verbose_name="字段类型"),
                ),
                ("binding_key", models.CharField(max_length=50, verbose_name="绑定键")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "input_type",
                    models.CharField(
                        default="input", max_length=20, verbose_name="输入类型"
                    ),
                ),
                (
                    "connected_table",
                    models.JSONField(default=list, verbose_name="关联表"),
                ),
                (
                    "new_valid_rule",
                    models.CharField(
                        choices=[
                            ("required", "必填"),
                            ("requiredReverse", "不必填"),
                            ("defaultNull", "默认空值"),
                            ("defaultField", "默认字段"),
                        ],
                        default="required",
                        max_length=20,
                        verbose_name="新值验证规则",
                    ),
                ),
                (
                    "origin_valid_rule",
                    models.CharField(
                        choices=[
                            ("required", "必填"),
                            ("requiredReverse", "不必填"),
                            ("defaultNull", "默认空值"),
                            ("defaultField", "默认字段"),
                        ],
                        default="required",
                        max_length=20,
                        verbose_name="原值验证规则",
                    ),
                ),
                (
                    "origin_default_value",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="原值默认值",
                    ),
                ),
                (
                    "new_default_value",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="新值默认值",
                    ),
                ),
                (
                    "main_field",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="主字段名"
                    ),
                ),
                (
                    "sub_fields",
                    models.JSONField(default=list, verbose_name="子字段配置"),
                ),
                ("options", models.JSONField(default=list, verbose_name="选项配置")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "form_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_items",
                        to="work_tools2.formconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "更新字段配置",
                "verbose_name_plural": "更新字段配置",
                "db_table": "work_tools2_formupdateitem",
                "ordering": ["sort_order"],
            },
        ),
    ]
