# Generated by Django 6.0.2 on 2026-03-02 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="菜单名称")),
                (
                    "pinyin",
                    models.CharField(blank=True, max_length=100, verbose_name="拼音"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="图标"),
                ),
                (
                    "url",
                    models.CharField(blank=True, max_length=200, verbose_name="URL"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="是否显示"),
                ),
                (
                    "group_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="分组名称"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="work_tools2.menu",
                        verbose_name="父级菜单",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜单",
                "verbose_name_plural": "菜单",
                "ordering": ["group_name", "sort_order"],
            },
        ),
    ]
