# Generated by Django 6.0.2 on 2026-04-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formupdateitem",
            name="component_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="引用配置项名称"
            ),
        ),
    ]
