# Generated by Django 6.0.2 on 2026-04-10 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0002_formupdateitem_component_name_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="配置项名称"
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[("select", "下拉框"), ("radio", "单选框")],
                        default="select",
                        max_length=20,
                        verbose_name="组件类型",
                    ),
                ),
                ("options", models.JSONField(default=list, verbose_name="选项配置")),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="使用次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "组件配置项",
                "verbose_name_plural": "组件配置项",
                "db_table": "work_tools2_componentconfig",
                "ordering": ["-created_at"],
            },
        )
    ]
