# Generated by Django 6.0.2 on 2026-04-11 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0003_componentconfig_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="formupdateitem",
            name="main_table",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="主表名"
            ),
        )
    ]
