# Generated by Django 6.0.2 on 2026-04-12 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0004_formupdateitem_main_table_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="formupdateitem",
            name="expressions",
            field=models.JSONField(default=dict, verbose_name="计算表达式配置"),
        ),
    ]
