# Generated by Django 6.0.2 on 2026-04-12 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0005_formupdateitem_expressions_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseIPConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="配置名称"
                    ),
                ),
                ("ip_address", models.CharField(max_length=50, verbose_name="IP地址")),
                (
                    "database_name",
                    models.CharField(max_length=100, verbose_name="数据库名"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="用户名"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="密码"
                    ),
                ),
                ("port", models.IntegerField(default=3306, verbose_name="端口号")),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("mysql", "MySQL"),
                            ("postgresql", "PostgreSQL"),
                            ("oracle", "Oracle"),
                            ("sqlserver", "SQL Server"),
                        ],
                        default="mysql",
                        max_length=20,
                        verbose_name="数据库类型",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "数据库IP配置",
                "verbose_name_plural": "数据库IP配置",
                "db_table": "work_tools2_databaseipconfig",
                "ordering": ["-created_at"],
            },
        ),

    ]
