# Generated by Django 6.0.2 on 2026-04-12 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0006_databaseipconfig_menu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="databaseipconfig",
            name="db_type",
        ),
        migrations.RemoveField(
            model_name="databaseipconfig",
            name="password",
        ),
        migrations.RemoveField(
            model_name="databaseipconfig",
            name="remark",
        ),
        migrations.RemoveField(
            model_name="databaseipconfig",
            name="username",
        ),

    ]
