# Generated by Django 6.0.2 on 2026-04-12 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0007_remove_databaseipconfig_db_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="databaseipconfig",
            name="port",
        ),
    ]
