# Generated by Django 6.0.2 on 2026-04-12 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0008_remove_databaseipconfig_port_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="formconfig",
            name="database_ip_ids",
            field=models.JSONField(default=list, verbose_name="数据库IP配置ID列表"),
        )
    ]
