# Generated by Django 6.0.2 on 2026-04-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0009_formconfig_database_ip_ids_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilePathConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="配置名称"
                    ),
                ),
                (
                    "base_path",
                    models.CharField(max_length=500, verbose_name="基础路径"),
                ),
                (
                    "save_mode",
                    models.CharField(
                        choices=[
                            ("single", "单一文件夹模式"),
                            ("date_layered", "按日期分层模式"),
                        ],
                        default="single",
                        max_length=20,
                        verbose_name="保存模式",
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("ymd_slash", "年/月/日 (2025/12/07)"),
                            ("ymd_concat", "年月日 (20251207)"),
                            ("ym_slash_d", "年月/日 (202512/07)"),
                            ("week", "按周格式 (20251207-20251212)"),
                        ],
                        default="ymd_slash",
                        max_length=20,
                        verbose_name="日期格式",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认配置"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="备注说明"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "文件输出路径配置",
                "verbose_name_plural": "文件输出路径配置",
                "db_table": "work_tools2_filepathconfig",
                "ordering": ["-is_default", "-created_at"],
            },
        )
    ]
