# Generated by Django 5.2.8 on 2026-07-02 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0012_formconfig_append_ops_remark"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportTaskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(max_length=32, unique=True, verbose_name="任务ID"),
                ),
                (
                    "table_name",
                    models.CharField(max_length=200, verbose_name="目标表名"),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="原始文件名",
                    ),
                ),
                ("file_content", models.TextField(verbose_name="CSV文件内容")),
                (
                    "truncate_before",
                    models.BooleanField(default=False, verbose_name="导入前清空"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "进行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度百分比")),
                (
                    "total_records",
                    models.IntegerField(default=0, verbose_name="总记录数"),
                ),
                (
                    "processed_records",
                    models.IntegerField(default=0, verbose_name="已处理记录数"),
                ),
                (
                    "inserted_count",
                    models.IntegerField(default=0, verbose_name="成功插入数"),
                ),
                ("failed_count", models.IntegerField(default=0, verbose_name="失败数")),
                ("errors", models.JSONField(default=list, verbose_name="错误详情")),
                (
                    "message",
                    models.TextField(blank=True, default="", verbose_name="任务消息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "导入任务",
                "verbose_name_plural": "导入任务",
                "db_table": "work_tools2_importtask",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="filepathconfig",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("ymd_slash", "年/月/日 (2025/12/07)"),
                    ("ymd_concat", "年月日 (20251207)"),
                    ("ym_slash_d", "年月/日 (202512/07)"),
                    ("week", "按周格式 (202512\\20251207-20251212)"),
                ],
                default="ymd_slash",
                max_length=20,
                verbose_name="日期格式",
            ),
        ),
    ]
