# Generated by Django 6.0.2 on 2026-07-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "work_tools2",
            "0013_importtaskmodel_alter_filepathconfig_date_format_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="importtaskmodel",
            name="file_path",
            field=models.CharField(
                blank=True, default="", max_length=1000, verbose_name="CSV文件路径"
            ),
        ),
        migrations.AlterField(
            model_name="importtaskmodel",
            name="file_content",
            field=models.TextField(blank=True, default="", verbose_name="CSV文件内容"),
        ),
    ]
