# Generated by Django 6.0.2 on 2026-07-03 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0014_importtaskmodel_file_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formconfig",
            name="call_count",
            field=models.IntegerField(default=0, verbose_name="调用次数"),
        ),
        migrations.AddField(
            model_name="formconfig",
            name="last_called_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最后调用时间"
            ),
        ),
        migrations.CreateModel(
            name="FormUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("dynamic", "动态表单"), ("merge", "表单合并")],
                        default="dynamic",
                        max_length=20,
                        verbose_name="调用来源",
                    ),
                ),
                (
                    "called_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="调用时间"),
                ),
                (
                    "form_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="work_tools2.formconfig",
                        verbose_name="表单配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "表单调用日志",
                "verbose_name_plural": "表单调用日志",
                "db_table": "work_tools2_formusagelog",
                "ordering": ["-called_at"],
            },
        ),
    ]
