# Generated by Django 6.0.2 on 2026-07-03 09:02

from django.db import migrations


def create_usage_statistics_menu(apps, schema_editor):
    Menu = apps.get_model("work_tools2", "Menu")
    if not Menu.objects.filter(url="/usage_statistics/").exists():
        Menu.objects.create(
            name="使用统计",
            pinyin="shiyongtongji",
            icon="bi-graph-up-arrow",
            url="/usage_statistics/",
            sort_order=999,
            is_visible=True,
            group_name="系统设置",
        )


def remove_usage_statistics_menu(apps, schema_editor):
    Menu = apps.get_model("work_tools2", "Menu")
    Menu.objects.filter(url="/usage_statistics/").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0016_create_menu_model"),
    ]

    operations = [
        migrations.RunPython(create_usage_statistics_menu, remove_usage_statistics_menu),
    ]
