# Generated by Django 6.0.2 on 2026-07-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0017_auto_20260703_1702"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="menu",
            table=None,
        ),
    ]
