# Generated by Django 6.0.2 on 2026-07-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0018_alter_menu_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="formqueryitem",
            name="expressions",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="计算表达式配置"
            ),
        ),
    ]
