# Generated by Django 6.0.2 on 2026-07-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0019_formqueryitem_expressions"),
    ]

    operations = [
        migrations.AddField(
            model_name="formconfig",
            name="table_aliases",
            field=models.JSONField(blank=True, default=dict, verbose_name="表别名映射"),
        ),
    ]
