# Generated by Django 6.0.2 on 2026-07-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0020_formconfig_table_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="formupdateitem",
            name="backward_expressions",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="回退计算表达式配置"
            ),
        ),
        migrations.AddField(
            model_name="formupdateitem",
            name="split_expression",
            field=models.BooleanField(
                default=False, verbose_name="执行回退表达式不一致"
            ),
        ),
    ]
