# Generated by Django 6.0.2 on 2026-07-04 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0021_formupdateitem_backward_expressions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="文档标题")),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", verbose_name="文档内容(HTML)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="分类"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "文档库",
                "verbose_name_plural": "文档库",
                "db_table": "work_tools2_documentlibrary",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("image", "图片"), ("file", "附件")],
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="document_library/%Y/%m/", verbose_name="文件"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="work_tools2.documentlibrary",
                        verbose_name="所属文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档附件",
                "verbose_name_plural": "文档附件",
                "db_table": "work_tools2_documentattachment",
            },
        ),
        migrations.AddField(
            model_name="formconfig",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_forms",
                to="work_tools2.documentlibrary",
                verbose_name="关联说明文档",
            ),
        ),
    ]
