# Generated by Django 6.0.2 on 2026-07-04 03:40

from django.db import migrations


def add_document_library_menu(apps, schema_editor):
    """在侧边栏添加文档库菜单入口"""
    Menu = apps.get_model('work_tools2', 'Menu')

    # 如果已经存在则不再创建
    if Menu.objects.filter(url='/document-library/').exists():
        return

    # 获取当前最大排序号
    max_sort = Menu.objects.filter(parent_id__isnull=True).count()

    Menu.objects.create(
        name='文档库',
        url='/document-library/',
        icon='bi-journal-bookmark-fill',
        parent_id=None,
        sort_order=max_sort,
        is_visible=True,
        group_name='主菜单',
        pinyin='wenkuku',
    )


def remove_document_library_menu(apps, schema_editor):
    """回滚时删除文档库菜单"""
    Menu = apps.get_model('work_tools2', 'Menu')
    Menu.objects.filter(url='/document-library/').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0022_documentlibrary_documentattachment_and_more"),
    ]

    operations = [
        migrations.RunPython(add_document_library_menu, remove_document_library_menu),
    ]
