# Generated by Django 6.0.2 on 2026-07-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0023_add_document_library_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentlibrary",
            name="content_json",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="编辑器JSON数据"
            ),
        ),
    ]
