# Generated by Django 6.0.2 on 2026-07-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0024_documentlibrary_content_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentlibrary",
            name="category",
        ),
    ]
