# Generated by Django 6.0.2 on 2026-07-05 10:07

from django.db import migrations, models


SYSTEM_TABLES = {
    'django_migrations', 'django_content_type', 'auth_permission', 'auth_group',
    'auth_user', 'auth_user_groups', 'auth_user_user_permissions', 'auth_group_permissions',
    'django_admin_log', 'django_session', 'work_tools2_formconfig', 'work_tools2_formqueryitem',
    'work_tools2_formupdateitem', 'work_tools2_componentconfig', 'work_tools2_menu',
    '_table_metadata', 'work_tools2_databaseipconfig', 'work_tools2_filepathconfig',
    '_query_sql_config', 'work_tools2_importtask', '_table_row_count',
}


def init_row_counts(apps, schema_editor):
    """初始化所有非系统表的行数缓存"""
    from django.db import connection
    TableRowCount = apps.get_model('work_tools2', 'TableRowCount')

    with connection.cursor() as cursor:
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")
        table_names = [row[0] for row in cursor.fetchall()]

    for table_name in table_names:
        if table_name in SYSTEM_TABLES or table_name.startswith('django_'):
            continue
        try:
            with connection.cursor() as cursor:
                cursor.execute(f"SELECT COUNT(*) as count FROM {table_name}")
                count = cursor.fetchone()[0]
            TableRowCount.objects.create(table_name=table_name, row_count=count)
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0027_analyze_database"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableRowCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_name",
                    models.CharField(max_length=200, unique=True, verbose_name="表名"),
                ),
                ("row_count", models.IntegerField(default=0, verbose_name="行数")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "表行数缓存",
                "verbose_name_plural": "表行数缓存",
                "db_table": "_table_row_count",
            },
        ),
        migrations.RunPython(init_row_counts, migrations.RunPython.noop),
    ]
