# Generated by Django 6.0.2 on 2026-07-05 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0028_tablerowcount"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablerowcount",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
    ]
