# Generated by Django 6.0.2 on 2026-07-05 10:18

from django.db import migrations, models


def init_import_configs(apps, schema_editor):
    """为所有非 SQLite 内部表初始化导入配置（默认允许导入）"""
    from django.db import connection
    TableImportConfig = apps.get_model('work_tools2', 'TableImportConfig')

    with connection.cursor() as cursor:
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")
        table_names = [row[0] for row in cursor.fetchall()]

    for table_name in table_names:
        try:
            TableImportConfig.objects.create(table_name=table_name, allow_import=True)
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0029_tablerowcount_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableImportConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_name",
                    models.CharField(max_length=200, unique=True, verbose_name="表名"),
                ),
                (
                    "allow_import",
                    models.BooleanField(default=True, verbose_name="允许导入"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "表导入配置",
                "verbose_name_plural": "表导入配置",
                "db_table": "_table_import_config",
            },
        ),
        migrations.RunPython(init_import_configs, migrations.RunPython.noop),
    ]
