# Generated by Django 6.0.2 on 2026-07-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0030_tableimportconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="formconfig",
            name="table_joins",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JOIN 配置列表",
                verbose_name="表关联关系",
            ),
        ),
    ]
