# Generated by Django 6.0.2 on 2026-07-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0031_formconfig_table_joins"),
    ]

    operations = [
        migrations.AddField(
            model_name="formqueryitem",
            name="backward_expressions",
            field=models.JSONField(
                blank=True, default=list, verbose_name="回退表达式配置"
            ),
        ),
        migrations.AddField(
            model_name="formqueryitem",
            name="split_expression",
            field=models.BooleanField(
                default=False, verbose_name="执行回退表达式不一致"
            ),
        ),
        migrations.AlterField(
            model_name="formqueryitem",
            name="expressions",
            field=models.JSONField(
                blank=True, default=list, verbose_name="计算表达式配置"
            ),
        ),
        migrations.AlterField(
            model_name="formupdateitem",
            name="backward_expressions",
            field=models.JSONField(
                blank=True, default=list, verbose_name="回退计算表达式配置"
            ),
        ),
        migrations.AlterField(
            model_name="formupdateitem",
            name="expressions",
            field=models.JSONField(default=list, verbose_name="计算表达式配置"),
        ),
    ]
