# Generated by Django 6.0.2 on 2026-07-07 07:52

from django.db import migrations


def convert_dict_to_list(value):
    """将 {tableName: expression} 转换为 [{tableName: ..., expression: ...}, ...]"""
    if not value:
        return []
    if isinstance(value, dict):
        return [
            {"tableName": k, "expression": str(v)}
            for k, v in value.items()
            if v is not None and str(v).strip()
        ]
    if isinstance(value, list):
        return value
    return []


def migrate_expressions_forward(apps, schema_editor):
    FormQueryItem = apps.get_model("work_tools2", "FormQueryItem")
    FormUpdateItem = apps.get_model("work_tools2", "FormUpdateItem")

    for item in FormQueryItem.objects.all():
        changed = False
        if isinstance(item.expressions, dict):
            item.expressions = convert_dict_to_list(item.expressions)
            changed = True
        if isinstance(item.backward_expressions, dict):
            item.backward_expressions = convert_dict_to_list(item.backward_expressions)
            changed = True
        if changed:
            item.save(update_fields=["expressions", "backward_expressions"])

    for item in FormUpdateItem.objects.all():
        changed = False
        if isinstance(item.expressions, dict):
            item.expressions = convert_dict_to_list(item.expressions)
            changed = True
        if isinstance(item.backward_expressions, dict):
            item.backward_expressions = convert_dict_to_list(item.backward_expressions)
            changed = True
        if changed:
            item.save(update_fields=["expressions", "backward_expressions"])


def migrate_expressions_backward(apps, schema_editor):
    """反向迁移：list 转 dict（会丢失同表多表达式）"""
    FormQueryItem = apps.get_model("work_tools2", "FormQueryItem")
    FormUpdateItem = apps.get_model("work_tools2", "FormUpdateItem")

    def list_to_dict(value):
        if not value:
            return {}
        if isinstance(value, list):
            return {entry["tableName"]: entry["expression"] for entry in value if entry.get("tableName")}
        if isinstance(value, dict):
            return value
        return {}

    for item in FormQueryItem.objects.all():
        changed = False
        if isinstance(item.expressions, list):
            item.expressions = list_to_dict(item.expressions)
            changed = True
        if isinstance(item.backward_expressions, list):
            item.backward_expressions = list_to_dict(item.backward_expressions)
            changed = True
        if changed:
            item.save(update_fields=["expressions", "backward_expressions"])

    for item in FormUpdateItem.objects.all():
        changed = False
        if isinstance(item.expressions, list):
            item.expressions = list_to_dict(item.expressions)
            changed = True
        if isinstance(item.backward_expressions, list):
            item.backward_expressions = list_to_dict(item.backward_expressions)
            changed = True
        if changed:
            item.save(update_fields=["expressions", "backward_expressions"])


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools2", "0032_formqueryitem_backward_expressions_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_expressions_forward, migrate_expressions_backward),
    ]
